cluster:
  name: hello-dev
  address: https://2DC4BF72363C5E61F0F3F62D5394FCE3.gr7.us-east-1.eks.amazonaws.com
nginx:
  image: nginx
  tag: 1.23.1
  labels: 
    environment: production
guestbook:
  image: gcr.io/heptio-images/ks-guestbook-demo
  tag: 0.2
  labels: 
    environment: development
